@startuml pe-na-pedra
left to right direction

:Administrador: as adm
:Trilheiro: as tr

rectangle aplicação {
  rectangle administração {
    usecase uc1 as "Banir \n membros\n 
      == CU1"
    usecase uc2 as "Mapear \n rotas\n 
      == CU2"
    usecase uc3 as "Vizualizar \n trilhas\n 
      == CU3"
    usecase uc4 as "Criar \n trilha\n 
      == CU4"
    usecase uc5 as "Excluir \n trilha\n 
      == CU5"
    usecase uc6 as "Atualizar \n trilha\n 
      == CU6"
    usecase uc7 as "Criar calendário \n mensal de \n trilhas\n 
      == CU7"
    usecase uc22 as "Definir ponto \n de encontro\n 
      == CU22"
    usecase uc23 as "Confirmar pagamento \n da trilha\n 
      == CU23"
    usecase uc13 as "Definir novos \n administradores\n 
      == CU13"
    usecase uc18 as "Remover \n administradores\n 
      == CU18"
    usecase uc19 as "Definir regras para \n trilhas\n 
      == CU19"
    usecase uc26 as "Editar ponto de \n encontro\n 
      == CU26"
    usecase uc28 as "Desbanir \n membros\n 
      == CU28"
    usecase uc29 as "Ver membros \n banidos\n 
      == CU29"
    usecase uc30 as "Ver \n trilheiros\n 
      == CU30"
  }
  
  rectangle trilheiro {
    usecase uc8 as "Vizualizar \n ponto de \n encontro\n 
      == CU8"
    usecase uc9 as "Se inscrever \n em trilha\n 
      == CU9"
    usecase uc10 as "Ofertar carona\n 
      == CU10"
    usecase uc11 as "Pegar carona\n 
      == CU11"
    usecase uc20 as "Criar perfil\n <<Única vez>>\n 
      == CU20"
    usecase uc12 as "Ajudar carona\n 
      == CU12"
    usecase uc14 as "Compartilhar trilha \n nos stories \n do Instagram\n 
      == CU14"
    usecase uc15 as "Cancelar inscrição \n em trilha\n 
      == CU15"
    usecase uc16 as "Editar perfil\n 
      == CU16"
    usecase uc17 as "Apagar conta\n <<Única vez>>\n 
      == CU17"
    usecase uc21 as "Pagar pro trilha\n 
      == CU21"
  }

  usecase uc24 as "Atulizar lista \n de \n trilheiros\n 
    == CU24"
  usecase uc25 as "Atulizar número \n de vagas da carona\n 
    == CU25"
  usecase uc27 as "Notificar ADM \n pagamento da taxa de inscrição \n da trilha\n 
    == CU27"


  uc15 .. uc24
  uc9 .. uc24
  uc23 .. uc24
  uc11 .. uc25
  uc21 .. uc27
  uc27 .. uc23
}


note right of uc24
  No máximo 30 trilheiros.
end note
 

note left of uc1
  Administradores podem ser banidos assim como
  os trilheiros comuns, caso venham a desrespeitar
  as normas do grupo.
end note

note left of uc17
  Administradores não podem apagar conta, caso
  o individuo queira sair, sendo administrador, ele 
  terá que ser removido do grupo de 
  aministradores e assim remover sua conta.
end note

note left of uc16
  Informar nome, email, whatsapp, alergias,
  dependentes, caso tenha, foto de perfil,
  data de nascimento, entre outras informações.
end note

note left of uc20
  Informar nome, email, whatsapp, alergias,
  dependentes, caso tenha, foto de perfil,
  data de nascimento, entre outras informações.
end note

note left of uc21
  Algumas trilhas ocorrem em localidades privadas,
  portanto, é necessário uma taxa de inscrição, logo, 
  um sistema de pagamento prévio seria cabível.
end note

note left of uc12
  Realizar uma transferencia pix 
  ou dinheiro físico caso o 
  trilheiro queira ajudar sua carona
  na gasolina, não é obrigatório.
end note

note right of uc10 
  Quem concede a carona deve indicar as condições,
  como, quem vai de moto, normalmente a carona tem
  que ter um capacete, ou indicar que tem um capacete reserva. Deve também indicar quantidades de vagas disponiveis.
end note

note left of uc10 
  Isso se o trilheiro tiver um veículo próprio.
end note

adm -left-> uc1
adm -left-> uc2
adm -left-> uc3
adm --> uc4
adm --> uc5
adm --> uc6
adm --> uc7
adm -left-> uc13
adm --> uc16
adm --> uc18
adm --> uc19
adm --> uc23
adm --> uc22
adm --> uc26
adm --> uc28
adm --> uc29
adm --> uc30

tr --> uc3
tr --> uc8
tr -left-> uc9
tr -left-> uc10
tr -left-> uc11
tr -left-> uc12
tr --> uc14
tr --> uc15
tr --> uc16
tr --> uc17
tr --> uc20
tr --> uc21
@enduml
