@startuml pe_na_pedra_usecase_7
  left to right direction

  package "Modelo de Caso de Uso- Pé na Pedra" {
    :Trilheiro: as tr

    rectangle aplicação {
      usecase uc24 as "Atulizar lista \n de \n trilheiros\n 
      == CU24"

      rectangle trilheiro {
        usecase uc20 as "Criar perfil\n <<Única vez>>\n 
          == CU20"
        usecase uc14 as "Compartilhar trilha \n nos stories \n do Instagram\n 
          == CU14"
        usecase uc15 as "Cancelar inscrição \n em trilha\n 
          == CU15"
      }
    }
  }

  note right of uc20
    Informar nome, email, whatsapp, alergias,
    dependentes, caso tenha, foto de perfil,
    data de nascimento, entre outras informações.
  end note

  note right of uc24
    No máximo 30 trilheiros.
  end note

  uc15 .. uc24

  tr --> uc20
  tr --> uc12
  tr --> uc14
  tr --> uc15
@enduml
