@startuml pe_na_pedra_class_diagram_4
package types {
  class JsonMap {
    <<typedef>>
    Map<String, dynamic>
  }
}

package controllers {
  class AuthFormController {
    - late String? _userId
    - String? _token
    - DateTime? _expiryDate
    - Timer? _logoutTimer

    - Future<void> _authenticate(JsonMap formData, String urlSegment)
    - void _autoLogout()
    + bool isAuth()
    + String? userId()
    + String? token()
    + Future<void> signup(BuildContext context, JsonMap formData)
    + Future<void> signIn(BuildContext context, JsonMap formData)
    + Future<void> tryAutoLogin()
    + void logout()
  }

  class TrailFormController {
    + FormData formData
    + nameValidator(String? value)
    + difficultyValidator(String? value)
    + locationValidator(String? value)
    + nameOnSaved(String? value, JsonMap formData)
    + difficultyOnSaved(String? value, JsonMap formData)
    + locationOnSaved(String? value, JsonMap formData)
    + onSubmit(BuildContext context, JsonMap formData)
  }
  
  class HikerEditFormController {
    + JsonMap formData
    + fullNameValidator(String? value)
    + addressValidator(String? value)
    + birthdayValidator(String? value)
    + imageUrlValidator(String? value)
    + fullNameOnSaved(String? value, JsonMap formData)
    + addressOnSaved(String? value, JsonMap formData)
    + birthdayOnSaved(String? value, JsonMap formData)
    + imageUrlOnSaved(String? value, JsonMap formData)
    + onSubmit(BuildContext context, JsonMap formData)
  }
}

TrailFormController --> JsonMap : use
HikerEditFormController --> JsonMap : use
AuthFormController --> JsonMap : use
@enduml
