@startuml pe_na_pedra_class_diagram_2
package types {
  class JsonMap {
    <<typedef>>
    Map<String, dynamic>
  }

  class TrailList {
    <<typedef>>
    List<Map<String, dynamic>>
  }

  class CoordinatesList {
    <<typedef>>
    List<CoordinatesModel>
  }

  class HikersList {
    <<typedef>>
    List<Hiker>
  }
}

package models {
  note "Modelo da trilha" as N3
  note "Modelo do calendário mensal de trilhas" as N4
  note "Modelo do evento" as N5

  class TrailModel {
    + String? id
    + String name
    + String difficulty
    + String location
    + CoordinatesList route
    + JsonMap toJson()
    + {static} void fromJson(JsonMap res)
  }

  class MonthlyTrailModel {
    + TrailList trails
    + JsonMap toJson()
    + {static} void fromJson(JsonMap res)
  }

  class EventModel {
    + HikersList hikers
    + TrailModel trail
    + CoordinatesModel meetingPoint
    + DateTime meetingTime
    + DateTime date
    + JsonMap toJson()
    + {static} void fromJson(JsonMap res)
  }

  TrailModel .. N3
  MonthlyTrailModel .. N4
  EventModel .. N5

  EventModel --> JsonMap : use
  MonthlyTrailModel --> JsonMap : use
  TrailModel --> JsonMap : use

  MonthlyTrailModel --> TrailList : use

  TrailModel --> TrailList : use

  EventModel --> HikersList : use
}
@enduml
