@startuml pe_na_pedra_class_diagram_3
package controllers {
  class EventController {
    + event: EventModel
    + EventController(event: EventModel): void
    + addHiker(hiker: HikerModel): void
    + removeHiker(hikerId: String): void
  }

  class MonthlyTrailController{
    + monthlyTrail: MonthlyTrailModel
    + MonthlyTrailController(monthlyTrail: MonthlyTrailModel): void
    + addTrail(trail: TrailModel, date: DateTime, meetingPoint: CoordinatesModel): void
    + removeTrail(trailId: String): void
  }
}
@enduml
