analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_local_variable: warning
    unused_import: error
    override_on_non_overriding_member: error
    parameter_assignments: warning

  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

lint:
  rules:
    # === ESTILO E ORGANIZAÇÃO ===
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    prefer_final_fields: true
    prefer_final_locals: true
    join_return_with_assignment: true
    unnecessary_parenthesis: true
    unnecessary_const: true
    unnecessary_this: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true

    # === PREVENÇÃO DE ERROS ===
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_catches_without_on_clauses: true
    avoid_types_on_closure_parameters: false
    null_check_on_nullable_type_parameter: true
    throw_in_finally: true

    # === BOA PRÁTICA DE CÓDIGO ===
    prefer_expression_function_bodies: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    require_trailing_commas: true # <<< INSERE VÍRGULAS AUTOMÁTICAS AO FORMATAR
    unnecessary_lambdas: true
    unnecessary_to_list_in_spreads: true
    avoid_multiple_declarations_per_line: true

    # === DART 3 / CLEAN CODE ===
    tighten_type_of_initializing_formals: true
    use_super_parameters: true
    use_decorated_box: true
    use_colored_box: true
    use_named_constants: true
    use_is_even_rather_than_modulo: true
    use_enums: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_renaming_method_parameters: true
    omit_local_variable_types: false

formatter:
  page_width: 100
  # Ativar vírgulas pendentes automaticamente (Dart >= 2.17)
  trailing_commas: automate
