@startuml pe_na_pedra_usecase_8
  left to right direction
  
  package "Modelo de Caso de Uso- Pé na Pedra" {
    :Trilheiro: as tr

    rectangle aplicação {
      rectangle trilheiro {
        usecase uc16 as "Editar perfil\n 
          == CU16"
        usecase uc17 as "Apagar conta\n <<Única vez>>\n 
          == CU17"
      }
    }
  }

  note right of uc16
    Informar nome, email, whatsapp, alergias,
    dependentes, caso tenha, foto de perfil,
    data de nascimento, entre outras informações.
  end note

  note right of uc17
    Administradores não podem apagar conta, caso
    o individuo queira sair, sendo administrador, ele 
    terá que ser removido do grupo de 
    aministradores e assim remover sua conta.
  end note

  tr --> uc16
  tr --> uc17
@enduml
