@startuml pe_na_pedra_class_diagram_1
package types {
  class JsonMap {
    <<typedef>>
    Map<String, dynamic>
  }
}

package models {
  note "Modelo do trilheiro" as N1
  note "Modelo de coordenadas do mapa" as N2

  class HikerModel {
    + id: String?
    + fullName: String
    + address: String
    + birthday: DateTime
    + imageUrl: String
    + isAdm: bool
    + toJson(): JsonMap
    + {static} HikerModel.fromJson(JsonMap res): void
  }

  class CoordinatesModel {
    + latitude: double
    + longitude: double
    + address: String
    + toJson(): JsonMap
    + {static} CoordinatesModel.fromJson(JsonMap res): void
  }

  HikerModel .. N1
  CoordinatesModel .. N2

  HikerModel --> JsonMap : use
  CoordinatesModel --> JsonMap : use
}
@enduml
