@startuml pe_na_pedra_class_diagram_3
package controllers {
  class EventController {
    + event: EventModel
    + EventController(event: EventModel): void
    + addHiker(hiker: HikerModel): void
    + removeHiker(hikerId: String): void
    + changeMeetingPoint(newMeetingPoint: CoordinatesModel): void
    + changeMeetingTime(newMeetingTime: DateTime): void
    + changeDate(newDate: DateTime): void
  }

  class MonthlyEventController{
    + monthlyEventModel: MonthlyEventModel
    + MonthlyEventController(monthlyEventModel: MonthlyEventModel): void
    + addEvent(event: Event): void
    + removeEvent(eventId: String): void
  }
}
@enduml
