@startuml pe_na_pedra_class_diagram_8
package types {
  class JsonMap {
    <<typedef>>
    Map<String, dynamic>
  }
}

package flutter {
  abstract class StatelessWidget {
  # build(context: BuildContext): Widget
  }

  abstract class StatefulWidget
}

package controller {
  class TrailFormController {
    + formData: JsonMap
  }

  class ProfileEditFormController {
    + formData: JsonMap
  }

  class BannedHikersController {
    + formData: JsonMap
  }

  class EventRegistratorController {
    + formData: JsonMap
  }

  class AdmsListViewController
}

package views {
  class AdmView {
    + build(context: BuildContext): Widget
  }

  class AdmsListView {
    + build(context: BuildContext): Widget
  }

  class EventRegistratorView {
    + build(context: BuildContext): Widget
  }

  class TrailsView {
    + build(context: BuildContext): Widget
  }

  class TrailFormView {
    + build(context: BuildContext): Widget
  }

  class ProfileView {
    + build(context: BuildContext): Widget
  }

  class ProfileEditView {
    + build(context: BuildContext): Widget
  }

  class BannedHikersView {
    + build(context: BuildContext): Widget
  }

  class HikersView {
    + build(context: BuildContext): Widget
  }
}

StatelessWidget <|-- AdmView
StatelessWidget <|-- ProfileView
StatefulWidget <|-- ProfileEditView
StatelessWidget <|-- AdmsListView
StatefulWidget <|-- EventRegistratorView
StatelessWidget <|-- TrailsView
StatelessWidget <|-- BannedHikersView
StatelessWidget <|-- HikersView

AdmView *-- ProfileView
ProfileView *-- ProfileEditView
AdmView *-- TrailsView
AdmView *-- BannedHikersView
AdmView *-- HikersView
AdmView *-- EventRegistratorView
AdmView *-- AdmsListView

TrailsView --> TrailFormView : use
ProfileEditView --> ProfileEditFormController : use

AdmsListView --> AdmsListViewController

TrailFormController --> JsonMap : use
ProfileEditFormController --> JsonMap : use

BannedHikersController --> JsonMap : use
EventRegistratorController --> JsonMap : use

BannedHikersView --> BannedHikersController

TrailFormView --> TrailFormController

StatefulWidget <|-- TrailFormView

EventRegistratorView --> EventRegistratorController : use
@enduml
