@startuml pe_na_pedra_class_diagram_2
package types {
  class JsonMap {
    <<typedef>>
    Map<String, dynamic>
  }

  class EventsList {
    <<typedef>>
    List<Map<String, dynamic>>
  }

  class CoordinatesList {
    <<typedef>>
    List<CoordinatesModel>
  }

  class HikersList {
    <<typedef>>
    List<Hiker>
  }
}

package models {
  note "Modelo da trilha" as N3
  note "Modelo do calendário mensal de trilhas" as N4
  note "Modelo do evento" as N5

  class TrailModel {
    + id: String?
    + name: String
    + difficulty: String
    + location: String
    + route: CoordinatesList
    + toJson(): JsonMap
    + {static} fromJson(JsonMap res): void
  }

  class MonthlyEventModel {
    + events: EventsList
    + toJson(): JsonMap
    + {static} fromJson(JsonMap res): void
  }

  class EventModel {
    + hikers: HikersList
    + trail: TrailModel
    + meetingPoint: CoordinatesModel
    + meetingTime: DateTime
    + date: DateTime
    + toJson(): JsonMap
    + {static} fromJson(res: JsonMap): void
  }

  TrailModel .. N3
  MonthlyEventModel .. N4
  EventModel .. N5

  EventModel --> JsonMap : use
  MonthlyEventModel --> JsonMap : use
  TrailModel --> JsonMap : use

  MonthlyEventModel --> EventsList : use

  TrailModel --> CoordinatesList : use

  EventModel --> HikersList : use
}
@enduml
