@startuml pe_na_pedra_class_diagram_5
package flutter {
  abstract class StatelessWidget {
    # build(context: BuildContext): Widget
  }

  abstract class StatefulWidget
}

package views {
  class AuthOrHomeView {
    + build(context: BuildContext): Widget
  }
  class AuthView {
    + build(context: BuildContext): Widget
  }
  class HomeView {
    + build(context: BuildContext): Widget
  }
  class SignUpView {
    + build(context: BuildContext): Widget
  }
  class SignInView {
    + build(context: BuildContext): Widget
  }
}

StatelessWidget <|-- AuthOrHomeView
StatelessWidget <|-- AuthView
StatelessWidget <|-- HomeView
StatefulWidget <|-- SignUpView
StatefulWidget <|-- SignInView
AuthOrHomeView *-- AuthView
AuthOrHomeView *-- HomeView
AuthView *-- SignUpView
AuthView *-- SignInView

package controller {
  class AuthFormController {
    - _userId: String? <<late>>
    - _token: String?
    - _expiryDate: DateTime?
    - _logoutTimer: Timer?

    - _authenticate(formData: JsonMap, urlSegment: String): Future<void>
    - _autoLogout(): void
    + isAuth(): bool
    + userId(): String?
    + token(): String?
    + signup(context: BuildContext, formData: JsonMap): Future<void>
    + signIn(context: BuildContext, formData: JsonMap): Future<void>
    + tryAutoLogin(): Future<void>
    + logout(): void
  }
}

package types {
  class JsonMap {
    <<typedef>>
    Map<String, dynamic>
  }
}

AuthFormController --> JsonMap : use

SignUpView --> AuthFormController : use
SignInView --> AuthFormController : use
@enduml
